-- A lexical scanner generated by aflex
with text_io; use text_io;
with lang_dfa; use lang_dfa; 
with lang_io; use lang_io; 
--# line 1 "lang.l"
--# line 6 "lang.l"

with lang_tokens;
use lang_tokens;
package lexical_a is
  procedure open(s: in string);
  procedure close;
  function YYlex return Token;
end a_lexic;
